version: "3"
services:
  nginx:
    image: nginx
    depends_on:
      - web1
      - web2
      - web3
    ports:
      - 8888:80
  web1:
    image: nginx
  web2:
    image: nginx
  web3:
    image: nginx
